# model
# dim-depth

seed: 233
name: megumin

defaults:
  - _self_
  - model: dit-768-12

dataset:
  data_dir: data/${name}
  meta_info_path: data/${name}/meta_info.json
  n_samples: ~
  max_frame_len: 256

vocoder:
  type: nsf-hifigan
  # ckpt: pretrained/vocoder/nsf_hifigan_44.1k_hop512_128bin_2024.02/model.ckpt
  ckpt: pretrained/vocoder/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.ckpt

training:
  # optimizer_type: adamwsf; learning_rate: 5e-5; weight_decay: 0.01; batch_size_per_gpu: 32; warmup_ratio: 0.05
  # 6000步就差不多了
  run_name: test
  learning_rate: 1.0e-4
  batch_size_per_gpu: 36
  max_steps: 10000
  decay_step: 1000  # 衰减间隔
  decay_rate: 0.6
  warmup_ratio: 0.05
  anneal_ratio: 0.2
  test_per_steps: 1500
  save_per_steps: ${training.test_per_steps}
  weight_decay: 0.01
  num_workers: 4
  optimizer_type: adamuon
  betas: (0.9, 0.95)
  grad_accumulation_steps: 1
  max_grad_norm: 0
  log_every_n_steps: 10
  log_media_per_steps: ${training.test_per_steps}
  resume_from_checkpoint: ~
  pretrained_path: pretrained/pretrain-v3_dit-768-12.ckpt
  # save_weights_only: false
  save_weights_only: true
  save_on_interruption: true
  eval_sample_steps: 32
  drop_spk_prob: 0.0
  time_schedule: lognorm
  # Logger options
  logger: tensorboard  # Options: "wandb" or "tensorboard"
  wandb_project: RIFT-SVC-FT
