seed: 233

defaults:
  - _self_
  - model: dit-512-8

dataset:
  data_dir: data/megumin
  meta_info_path: data/megumin/meta_info.json
  max_frame_len: 256

vocoder:
  type: nsf-hifigan
  ckpt: pretrained/vocoder/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.ckpt

training:
  run_name: test
  learning_rate: 6.0e-5
  batch_size_per_gpu: 80
  max_steps: 7000
  warmup_ratio: 0.05
  gamma: 0.9
  decay_step: 1500
  test_per_steps: 1000
  save_per_steps: 1500
  log_media_per_steps: 1500
  weight_decay: 0.01
  num_workers: 4
  optimizer_type: moun
  betas: (0.9, 0.95)
  grad_accumulation_steps: 1
  max_grad_norm: 0
  log_every_n_steps: 10
  resume_from_checkpoint: ~
  pretrained_path: pretrained/pretrain-v3_dit-512-8.ckpt
  # save_weights_only: false
  save_weights_only: true
  save_on_interruption: true
  eval_sample_steps: 32
  drop_spk_prob: 0.0
  time_schedule: lognorm
  # Logger options
  logger: tensorboard  # Options: "wandb" or "tensorboard"
  wandb_project: RIFT-SVC-FT
