seed: 233
name: megumin

defaults:
  - _self_
  # 将dit-base指定的值放到 model 键下面
  - model: dit-base

dataset:
  data_dir: data/${name}
  meta_info_path: data/${name}/meta_info.json
  n_samples: ~
  max_frame_len: 256
  # 是否懒加载数据，False则会在启动训练时将所有数据加载到内存
  lazy: False

vocoder:
  type: nsf-hifigan
  ckpt: pretrained/vocoder/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.ckpt

model:
  dim: 512
  depth: 8

training:
  run_name: test
  learning_rate: 1.0e-4
  batch_size_per_gpu: 80
  max_steps: 5200
  decay_step: 1500
  # decay_step: [1500, 4500, 5500]
  decay_rate: 0.5
  warmup_ratio: 0.05
  anneal_ratio: 0.2
  test_per_steps: 1000
  save_per_steps: 2000
  # save_per_steps: ${training.test_per_steps}
  weight_decay: 0.01
  num_workers: 4
  optimizer_type: adamuon
  # optimizer_type: muon
  betas: (0.9, 0.95)
  grad_accumulation_steps: 1
  max_grad_norm: 0
  log_every_n_steps: 10
  log_media_per_steps: ${training.test_per_steps}
  # 为空时若训练目录有历史权重，则会找最新的一个加载
  resume_from_checkpoint: ~
  pretrained_path: pretrained/pretrain-v3_dit-512-8.ckpt
  save_weights_only: false
  # save_weights_only: true
  save_on_interruption: true
  freeze_adaln_and_tembed: false
  eval_sample_steps: 32
  drop_spk_prob: 0.0
  time_schedule: lognorm
  # Logger options
  logger: tensorboard  # Options: "wandb" or "tensorboard"
  wandb_project: RIFT-SVC-FT
